//> using scala "3.2.2"
//> using repository "sonatype:snapshots"
//> using lib "org.scalameta::mdoc:2.3.7+2-f2af9b9a-SNAPSHOT"
//> using lib "org.planet42::laika-core:0.19.0"
//> using lib "org.planet42::laika-io:0.19.0"
//> using lib "works.scala::scala-cmd:0.0.2"